# SPDX-License-Identifier: MIT
"""Controller for Governance Document — the archive that has to outlive us.

THE CHAIN IS THE POINT. An operating agreement amended three times is four
documents, and the question somebody asks in 2050 is "which one was in force in
2031". That is answerable only if every amendment names what it replaces and
nothing in the chain loops. `validate` refuses a document that supersedes itself
and refuses a cycle, walking the chain rather than checking only one hop —
a two-document loop is just as unreadable as a one-document one.

`superseded_by` is written by whichever document names this one, not by hand.

────────────────────────────────────────────────────────────────────────────
v0.83.0: `on_trash` RELEASES THE ARCHIVE-COPY LINKS, AND ONLY THOSE
────────────────────────────────────────────────────────────────────────────

`generate_mobile_login_qr` can file the card it draws in this archive and record
where it went on `Mobile Access Grant.qr_document`. That link then made the
archived copy UNDELETABLE: Frappe's `check_if_doc_is_linked` refuses to delete a
document any Link field points at, so a card filed by mistake, or one belonging to
somebody who left two years ago, could not be cleared out without first hunting
down a read-only field on a register most people have never opened. The error
Frappe raises names the linking doctype and nothing about how to fix it.

`on_trash` runs BEFORE `check_if_doc_is_linked` in `frappe.model.delete_doc`, so
nulling the link there is enough: the delete then proceeds and the grant keeps
every other thing it knows.

IT IS DELIBERATELY NARROW, AND `ARCHIVE_LINKS` IS THE WHOLE OF IT. Seven other
doctypes link to Governance Document — Lease, Related Party, Parcel, Advisory
Agreement, Trade Shipment, Transfer Pricing Documentation and this doctype's own
`supersedes` — and every one of those is a REFERENCE: the lease is about that
agreement, and a delete that quietly detached them would destroy the fact that
they were ever connected, which is the one thing an archive exists to hold. Those
keep refusing, and they should.

THE TEST IS NOT "DOES THE LABEL SAY ARCHIVE", AND THAT MATTERS BECAUSE THREE
OTHER FIELDS WOULD PASS THAT TEST — `Lease.governance_document`,
`Parcel.appraisal_document` and `Advisory Agreement.document_reference` all
describe themselves as the filed copy of something. None of them is in the tuple.

THE TEST IS WHETHER THIS APP CAN REDRAW IT. A mobile card is regenerated by
`generate_mobile_login_qr` from data the grant still holds, so the filed PNG is a
convenience — the offline distribution path, per `tools/mobile._archive_card` —
and deleting it loses nothing. A lease's archive entry holds a signed instrument
that exists nowhere else on the site; releasing its link would turn a delete into
a one-click destruction of the only copy, which is the precise opposite of what
an archive is for.

So: the linking record must remain sufficient to reconstruct what was deleted.
Adding a link to this tuple means asserting that, and
`test_archive_link_release.EveryOtherLinkStillRefuses` holds the tuple to it.
"""

import frappe
from frappe import _
from frappe.model.document import Document

#: How far back the cycle check walks before giving up. A governance chain
#: hundreds long is not a chain, it is a bug, and either way refusing is right.
MAX_CHAIN = 200

#: `(doctype, fieldname)` for every link that points at an ARCHIVED COPY of
#: something this app can still produce, rather than at a document the linking
#: record is about. Only these are released on delete — see the module docstring
#: for why the distinction is the whole safety property, and why the other seven
#: links to this doctype go on refusing.
ARCHIVE_LINKS = (("Mobile Access Grant", "qr_document"),)


class GovernanceDocument(Document):
	def validate(self):
		if self.supersedes and self.supersedes == self.name:
			frappe.throw(_("A Governance Document cannot supersede itself."))
		self._refuse_cycle()

	def _refuse_cycle(self):
		seen = {self.name} if self.name else set()
		current = self.supersedes
		for _hop in range(MAX_CHAIN):
			if not current:
				return
			if current in seen:
				frappe.throw(
					_(
						"This would make the amendment chain loop back on itself at {0}. "
						"Supersedes has to point backwards in time."
					).format(current),
					title=_("Circular Amendment Chain"),
				)
			seen.add(current)
			current = frappe.db.get_value("Governance Document", current, "supersedes")
		frappe.throw(_("Amendment chain is longer than {0} documents; refusing.").format(MAX_CHAIN))

	def on_trash(self):
		"""Release the archive-copy links so the delete is not refused. v0.83.0.

		ORDER IS THE WHOLE MECHANISM: `frappe.model.delete_doc` runs `on_trash`
		and only then `check_if_doc_is_linked`, so by the time the link check
		looks there is no link left to find. Doing this in `after_delete` would
		be too late and doing it in `before_delete` would be earlier than it
		needs to be for no benefit.

		THE TIMESTAMP MOVES ON THE GRANT, which is not an oversight. A read-only
		field on that record changed and somebody reading its history should see
		that it did; suppressing `modified` would make the link appear to have
		never existed, and "the card was filed and then the file was deleted" is
		exactly the sort of thing an archive gets audited on.

		Best-effort on the schema, as everywhere else in this app: a site whose
		Mobile Access Grant predates `qr_document`, or which has no mobile
		surface at all, is skipped rather than raised at.
		"""
		for doctype, fieldname in ARCHIVE_LINKS:
			if not frappe.db.exists("DocType", doctype):
				continue
			try:
				if not frappe.get_meta(doctype).has_field(fieldname):
					continue
			except Exception:  # pragma: no cover - a site mid-migrate
				continue
			# `frappe.db.get_all` and not the permissioned reader: this is a
			# referential cleanup, and a link the current session cannot SEE is
			# still a link that would refuse the delete.
			for row in frappe.db.get_all(doctype, filters={fieldname: self.name}, fields=["name"]):
				frappe.db.set_value(doctype, row["name"], fieldname, None)
