# SPDX-License-Identifier: MIT
"""Comments and ToDos — the human layer on top of the documents.

`list_comments` checks read permission on the parent document, for the same
reason the attachment tools do: a comment thread is what people said to each
other about a document, not a field of it, and the document's own permission is
the only sensible gate on that.

TWO NAMING TRAPS IN ToDo, both handled here rather than passed to the caller:

  * **`owner` is not the assignee.** Frappe's `owner` is whoever created the row;
    the assignee is `allocated_to` (and was `owner` on versions before that field
    existed, which is where the confusion comes from). This module takes `owner`
    as the argument name — because that is what a caller means by "assign it to
    them" — and writes it to whichever field this site actually uses.
  * **There is no `subject` field.** ToDo has `description`, a rich-text field
    that the Desk renders as the whole task. A `subject` argument is folded in as
    the first line rather than dropped, and set on a real `subject` field on the
    sites that have added one.
"""

import frappe

from .. import compat
from ..args import as_filter, as_limit, as_str
from ..errors import ToolError
from ..result import ToolResult

TODO_PRIORITIES = ("Low", "Medium", "High")
TODO_STATUSES = ("Open", "Closed", "Cancelled")


# ── 25. list_comments ───────────────────────────────────────────────────────
def list_comments(args: dict) -> ToolResult:
	"""The comment and activity thread on one document."""
	doctype = as_str(args, "doctype", required=True)
	name = as_str(args, "name", required=True)
	comment_type = as_str(args, "comment_type")
	limit = as_limit(args)

	if not compat.doctype_exists(doctype):
		raise ToolError(f"no DocType named {doctype!r} on this site")
	if not frappe.db.exists(doctype, name):
		raise ToolError(f"no {doctype} named {name!r}")
	if not frappe.has_permission(doctype, "read", doc=name):
		raise ToolError(
			f"{frappe.session.user} is not permitted to read {doctype} {name}, so "
			"its comments are not available."
		)

	filters = {"reference_doctype": doctype, "reference_name": name}
	if comment_type:
		filters["comment_type"] = comment_type

	fields = compat.existing_fields(
		"Comment",
		[
			"name",
			"comment_type",
			"content",
			"comment_by",
			"comment_email",
			"owner",
			"creation",
			"modified",
			"subject",
		],
	)
	rows = frappe.db.get_all("Comment", filters=filters, fields=fields, order_by="creation asc", limit=limit)
	for row in rows:
		row["author"] = row.get("comment_by") or row.get("comment_email") or row.get("owner")
		row["added_on"] = row.get("creation")

	by_type = {}
	for row in rows:
		key = row.get("comment_type") or "Comment"
		by_type[key] = by_type.get(key, 0) + 1

	data = {
		"doctype": doctype,
		"name": name,
		"comments": rows,
		"count": len(rows),
		"limit": limit,
		"truncated": len(rows) == limit,
		"by_comment_type": by_type,
		"comment_type_filter": comment_type or None,
		"note": (
			"Frappe stores audit chatter in the same table as human comments. "
			"comment_type 'Comment' is what a person typed; 'Info', 'Assigned', "
			"'Workflow', 'Edit' and friends are generated by the framework."
		),
	}
	return ToolResult(data, f"{doctype} {name}: {len(rows)} comment row(s)")


# ── 26. list_assigned_todos ─────────────────────────────────────────────────
def list_assigned_todos(args: dict) -> ToolResult:
	"""ToDos assigned to somebody, open ones by default."""
	user = as_str(args, "user")
	status = as_filter(args, "status", default="Open")
	limit = as_limit(args)

	if user and not frappe.db.exists("User", user):
		raise ToolError(f"no User named {user!r}")
	if status and status not in TODO_STATUSES:
		raise ToolError(
			f"status must be one of {', '.join(TODO_STATUSES)} (or empty for all), got {status!r}"
		)

	assignee_field = _assignee_field()
	filters = {}
	if user:
		filters[assignee_field] = user
	if status:
		filters["status"] = status

	fields = compat.existing_fields(
		"ToDo",
		[
			"name",
			"status",
			"priority",
			"date",
			"description",
			"reference_type",
			"reference_name",
			"assigned_by",
			"allocated_to",
			"owner",
			"creation",
			"modified",
		],
	)
	rows = frappe.db.get_all(
		"ToDo",
		filters=filters,
		fields=fields,
		order_by="date asc, priority desc, creation asc",
		limit=limit,
	)
	for row in rows:
		row["assigned_to"] = row.get(assignee_field)

	overdue = 0
	today = frappe.utils.today()
	for row in rows:
		if row.get("date") and str(row["date"]) < today and row.get("status") == "Open":
			row["overdue"] = True
			overdue += 1
		else:
			row["overdue"] = False

	data = {
		"todos": rows,
		"count": len(rows),
		"overdue_count": overdue,
		"user": user or None,
		"status": status or "any",
		"limit": limit,
		"truncated": len(rows) == limit,
		"assignee_field": assignee_field,
		"note": (
			f"On this site the assignee lives in {assignee_field!r}; `owner` is "
			"whoever created the ToDo. `assigned_to` is normalised for you."
		),
	}
	scope = f" for {user}" if user else ""
	return ToolResult(data, f"{len(rows)} ToDo(s){scope} ({status or 'any status'})")


# ── 27. create_todo (MUTATING) ──────────────────────────────────────────────
def create_todo(args: dict) -> ToolResult:
	"""Assign a ToDo to a user.

	The gentlest mutating tool in the catalogue — a ToDo touches no ledger and
	submits nothing — but it does put an item in somebody's queue and send them a
	notification, which is why it is still off by default.
	"""
	subject = as_str(args, "subject", required=True)
	assignee = as_str(args, "owner", required=True)
	description = as_str(args, "description")
	priority = as_str(args, "priority", default="Medium")
	reference_doctype = as_str(args, "reference_doctype")
	reference_name = as_str(args, "reference_name")
	date = args.get("date")

	if priority not in TODO_PRIORITIES:
		raise ToolError(f"priority must be one of {', '.join(TODO_PRIORITIES)}, got {priority!r}")
	if not frappe.db.exists("User", assignee):
		raise ToolError(
			f"no User named {assignee!r}. `owner` is the person the ToDo is "
			"assigned to, and must be an existing User's email/name."
		)
	if not frappe.db.get_value("User", assignee, "enabled"):
		raise ToolError(f"User {assignee!r} is disabled and cannot be assigned work")

	if reference_doctype or reference_name:
		if not (reference_doctype and reference_name):
			raise ToolError("reference_doctype and reference_name go together — pass both or neither")
		if not compat.doctype_exists(reference_doctype):
			raise ToolError(f"no DocType named {reference_doctype!r} on this site")
		if not frappe.db.exists(reference_doctype, reference_name):
			raise ToolError(f"no {reference_doctype} named {reference_name!r}")

	due_date = None
	if date not in (None, ""):
		try:
			due_date = frappe.utils.getdate(date).isoformat()
		except Exception:
			raise ToolError(f"date must be YYYY-MM-DD, got {date!r}") from None

	assignee_field = _assignee_field()
	doc = frappe.new_doc("ToDo")
	doc.set(assignee_field, assignee)
	doc.status = "Open"
	doc.priority = priority
	if due_date:
		doc.date = due_date
	if reference_doctype:
		doc.reference_type = reference_doctype
		doc.reference_name = reference_name
	if compat.has_field("ToDo", "assigned_by"):
		doc.assigned_by = frappe.session.user

	folded = _fold_subject(doc, subject, description)
	doc.insert()

	data = {
		"name": doc.name,
		"assigned_to": assignee,
		"assignee_field": assignee_field,
		"assigned_by": doc.get("assigned_by"),
		"subject": subject,
		"status": "Open",
		"priority": priority,
		"date": due_date,
		"reference_type": reference_doctype or None,
		"reference_name": reference_name or None,
		"subject_handling": folded,
	}
	return ToolResult(
		data,
		f"created ToDo {doc.name} for {assignee} ({priority}): {subject}",
		docstatus_delta="none → 0 (draft)",
	)


def _fold_subject(doc, subject: str, description: str) -> str:
	"""Put `subject` where this site's ToDo will actually show it.

	Returns a short description of what was done, so the response does not
	quietly disagree with the caller about where their text went.
	"""
	if compat.has_field("ToDo", "subject"):
		doc.set("subject", subject)
		doc.description = description or subject
		return "subject field (this site's ToDo has one)"
	doc.description = f"{subject}\n\n{description}" if description else subject
	return "folded into description (ToDo has no subject field)"


def _assignee_field() -> str:
	"""`allocated_to` on modern Frappe, `owner` on versions before it existed."""
	return compat.first_field("ToDo", "allocated_to") or "owner"
